builders:
  value_class:
    import: "package:value_class/value_class.dart"
    builder_factories: [ "builder" ]
    build_extensions: { ".dart": [ ".value.dart" ] }
    auto_apply: dependents
    build_to: source
    runs_before: [ "json_serializable" ]
