targets:
  $default:
    builders:
      value_class:
        generate_for:
          include:
            - example/example.dart

builders:
  value_class:
    import: "package:value_class/value_class.dart"
    builder_factories: [ "builder" ]
    build_extensions: { ".dart": [ ".value.dart" ] }
    auto_apply: dependents
    build_to: source
