name: value_class
description: >
  Code generation for value classes.
  This package depends on value_annotation.
version: 1.0.0
homepage: https://github.com/blendthink/value_class.dart

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  analyzer: ">=2.4.0 <5.0.0"
  build: ^2.3.0
  build_config: ^1.1.0
  collection: ^1.16.0
  source_gen: ^1.2.2
  value_annotation: ^1.0.0

dev_dependencies:
  build_test: ^2.1.5
  build_runner: ^2.2.0
  matcher: ^0.12.12
  source_gen_test: ^1.0.3
  test: ^1.21.4
