name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: [ "feature", "triage" ]
assignees:
  - blendthink
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What inspired this feature request? What problems were you facing?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Detailed description of requirements of implementation.
    validations:
      required: true
