name: check-publish

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'packages/value_annotation/pubspec.yaml'
      - 'packages/value_class/pubspec.yaml'

jobs:
  check-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ value_annotation, value_class ]
    if: github.event.pull_request.merged == false && startsWith(github.head_ref, 'release/')
    steps:
      - uses: actions/checkout@v3
      - id: pubspec-version
        name: pubspec version
        run: .github/scripts/diff-pubspec-version.sh
        env:
          PACKAGE: ${{ matrix.package }}
      - if: ${{ steps.pubspec-version.outputs.isNotEmpty == 'true' }}
        uses: dart-lang/setup-dart@v1.3
      - if: ${{ steps.pubspec-version.outputs.isNotEmpty == 'true' }}
        name: copy credentials
        run: .github/scripts/copy-credentials.sh
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
      - if: ${{ steps.pubspec-version.outputs.isNotEmpty == 'true' }}
        name: check publish
        run: dart pub publish --dry-run
        working-directory: packages/${{ matrix.package }}
