name: check-pr

on:
  pull_request:
    paths:
      - 'packages/value_annotation/lib/**/*.dart'
      - 'packages/value_annotation/pubspec.yaml'
      - 'packages/value_class/lib/**/*.dart'
      - 'packages/value_class/test/**/*.dart'
      - 'packages/value_class/analysis_options.yaml'
      - 'packages/value_class/build.yaml'
      - 'packages/value_class/pubspec.yaml'

jobs:
  check-pr:
    env:
      PACKAGE: packages/value_class
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.PACKAGE }}
    strategy:
      matrix:
        sdk: [ 2.14, 2.15, 2.16, 2.17 ]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ matrix.sdk }}
      - uses: actions/cache@v3
        with:
          path: |
            ${{ env.PUB_CACHE }}
            ${{ github.workspace }}/${{ env.PACKAGE }}/.packages
            ${{ github.workspace }}/${{ env.PACKAGE }}/.dart_tool/package_config.json
          key: pubspec-${{ hashFiles(format('{0}{1}{2}', github.workspace, env.PACKAGE, '/pubspec.yaml')) }}-${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze code
        run: dart analyze
      - name: Run tests
        run: dart test
