name: publish

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'packages/value_annotation/pubspec.yaml'
      - 'packages/value_class/pubspec.yaml'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ value_annotation, value_class ]
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    steps:
      - uses: actions/checkout@v3
      - id: pubspec-version
        name: pubspec version
        run: .github/scripts/release-pubspec-version.sh
        env:
          PACKAGE: ${{ matrix.package }}
      - uses: dart-lang/setup-dart@v1.3
      - name: copy credentials
        run: .github/scripts/copy-credentials.sh
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
      - name: publish
        run: dart pub publish --force
        working-directory: packages/${{ matrix.package }}
      - name: push tag
        run: .github/scripts/push-tag.sh
        env:
          PACKAGE: ${{ matrix.package }}
          VERSION: ${{ steps.pubspec-version.outputs.version }}
